package com.olxseller.olx.helper;

public enum OrderStatus { 
  PENDING, CONFIRMED, PROCESSING, ON_HOLD, SHIPPED, IN_TRANSIT, OUT_FOR_DELIVERY,
  DELIVERED, CANCELLED, RETURNED, REFUNDED, FAILED
}
// PENDING,COMPLETED,FAILED,CANCELLED, REFUNDED
